product_feed.xml:
  path: '/product.xml'
  defaults:
    _controller: '\Drupal\product_feed\Controller\ProductFeedController::feed'
    _title: 'Product feed'
  requirements:
    _permission: 'access content'
  options:
    _format: 'xml'
